import React, { useState, useRef, useEffect, useCallback } from 'react';
import { Send, Bot, User, Loader2, Globe, Terminal, Plus, ShieldAlert, Hexagon, Activity, Brain, Server as ServerIcon, Wifi, FileText, AlertOctagon, Download, Play, FileCode, FolderOpen, ChevronRight, ChevronDown, X, MonitorPlay, ArrowUpCircle, PanelLeftClose, PanelLeft, MoreHorizontal, Edit2, Trash2, CreditCard, Settings, LogOut, Sun, Moon, Check, Code2, ChevronUp } from 'lucide-react';
import { generateDevOpsAdvice, extractNewKnowledge } from '../services/gemini';
import { ChatMessage, KnowledgeItem, AgentProfile, ChatSession, ProcessStep, TerminalLog, ViewState } from '../types';

// --- INITIAL DATA ---

const AGENTS: AgentProfile[] = [
  {
    id: 'user-ops',
    name: 'Внешний Ops',
    role: 'Администратор (SSH)',
    type: 'USER_SIDE',
    avatar: 'bg-indigo-600',
    level: 5,
    xp: 4500,
    nextLevelXp: 5000,
    totalActions: 124,
    skills: [
        { name: 'SSH/Paramiko', level: 5, progress: 90, description: 'Удаленное управление' },
        { name: 'Docker', level: 4, progress: 50, description: 'Оркестрация' }
    ]
  },
  {
    id: 'watchdog',
    name: 'Сторожевой Пёс',
    role: 'Внутренняя Безопасность',
    type: 'WATCHDOG',
    avatar: 'bg-red-700',
    level: 9,
    xp: 9900,
    nextLevelXp: 10000,
    totalActions: 850,
    skills: [
        { name: 'Анализ логов', level: 9, progress: 100, description: 'Поиск паттернов' },
        { name: 'Сканер уязвимостей', level: 8, progress: 80, description: 'CVE детекция' }
    ]
  }
];

// --- MOCK FILES ---
const MOCK_FILES = {
    'deploy.sh': `#!/bin/bash\n\n# Deployment Script v1.2\n# Generated by NexusOps AI\n\necho "[INFO] Starting deployment process..."\n\n# Check permissions\nif [ "$EUID" -ne 0 ]; then\n  echo "Please run as root"\n  exit\nfi\n\n# Update system\napt-get update && apt-get upgrade -y\n\n# Create directory\nmkdir -p /var/www/app\n\necho "[SUCCESS] Deployment completed."`,
    'index.html': `<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NexusOps Demo</title>
    <style>
        body { 
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; 
            background: #09090b; 
            color: #e4e4e7; 
            display: flex; 
            justify-content: center; 
            align-items: center; 
            height: 100vh; 
            margin: 0; 
        }
        .container { 
            background: #18181b; 
            padding: 2.5rem; 
            border-radius: 16px; 
            border: 1px solid #27272a; 
            text-align: center; 
            box-shadow: 0 10px 30px -10px rgba(0,0,0,0.5);
            max-width: 400px;
        }
        h1 { 
            color: #818cf8; 
            font-size: 1.5rem;
            margin-bottom: 1rem;
        }
        p { color: #a1a1aa; line-height: 1.5; margin-bottom: 1.5rem; }
        .btn { 
            background: #6366f1; 
            color: white; 
            border: none; 
            padding: 10px 24px; 
            border-radius: 8px; 
            cursor: pointer; 
            font-weight: 500;
            transition: all 0.2s;
        }
        .btn:hover { background: #4f46e5; transform: translateY(-1px); }
    </style>
</head>
<body>
    <div class="container">
        <h1>NexusOps Чат</h1>
        <p>Система успешно развернута на сервере. Приложение готово к работе.</p>
        <button class="btn" onclick="alert('Статус: Активно\\nВерсия: v2.1.0')">Проверить статус</button>
    </div>
</body>
</html>`,
    'docker-compose.yml': `version: '3.8'
services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
    restart: always`
};

// Interface extension for internal use
interface ExtendedChatMessage extends ChatMessage {
    thinkingDuration?: number;
    thinkingContent?: string;
}

interface AssistantProps {
    onViewChange?: (view: ViewState) => void;
}

export const Assistant: React.FC<AssistantProps> = ({ onViewChange }) => {
  // --- STATE ---
  const [currentAgentId, setCurrentAgentId] = useState<string>(AGENTS[0].id);
  const [sessions, setSessions] = useState<ChatSession[]>([
    {
      id: 'session-1',
      title: 'Настройка сервера',
      agentId: 'user-ops',
      lastModified: new Date(),
      messages: [{ id: '1', role: 'model', text: 'Агент готов к работе. Чем могу помочь с сервером?', timestamp: new Date() }]
    }
  ]);
  const [currentSessionId, setCurrentSessionId] = useState<string>('session-1');
  const [knowledgeBase, setKnowledgeBase] = useState<KnowledgeItem[]>([]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [thinkingTime, setThinkingTime] = useState(0);
  const [isConnected, setIsConnected] = useState(false);
  const [sshConfig, setSshConfig] = useState<{host: string, username: string} | null>(null);
  
  // UI State
  const [leftSidebarOpen, setLeftSidebarOpen] = useState(true);
  const [rightSidebarWidth, setRightSidebarWidth] = useState(400);
  const [isRightSidebarOpen, setIsRightSidebarOpen] = useState(true);
  const [activeRightTab, setActiveRightTab] = useState<'files' | 'preview'>('files');
  const [isResizing, setIsResizing] = useState(false);
  const [showUserMenu, setShowUserMenu] = useState(false);
  const [editingSessionId, setEditingSessionId] = useState<string | null>(null);
  const [editTitle, setEditTitle] = useState('');
  const [activeFilePreview, setActiveFilePreview] = useState<string | null>(null);

  const bottomRef = useRef<HTMLDivElement>(null);
  const timerRef = useRef<number | null>(null);
  const sidebarRef = useRef<HTMLDivElement>(null);

  // Derived
  const currentAgent = AGENTS.find(a => a.id === currentAgentId) || AGENTS[0];
  const currentSession = sessions.find(s => s.id === currentSessionId) || sessions[0];
  const currentMessages = currentSession.messages as ExtendedChatMessage[];

  // --- EFFECTS ---
  useEffect(() => {
    const savedKnowledge = localStorage.getItem('nexus_knowledge');
    if (savedKnowledge) setKnowledgeBase(JSON.parse(savedKnowledge));

    const savedSettings = localStorage.getItem('nexus_ssh_settings');
    if (savedSettings) {
      try {
        const parsed = JSON.parse(savedSettings);
        if (parsed.host && parsed.username) {
            setSshConfig(parsed);
        }
      } catch (e) { console.error(e); }
    }
  }, []);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [currentMessages, loading]);

  useEffect(() => {
      if (loading) {
          const startTime = Date.now();
          timerRef.current = window.setInterval(() => {
              setThinkingTime((Date.now() - startTime) / 1000);
          }, 100);
      } else {
          if (timerRef.current) clearInterval(timerRef.current);
          setThinkingTime(0);
      }
      return () => { if (timerRef.current) clearInterval(timerRef.current); };
  }, [loading]);

  // Resizer Logic
  const startResizing = useCallback(() => {
    setIsResizing(true);
  }, []);

  const stopResizing = useCallback(() => {
    setIsResizing(false);
  }, []);

  const resize = useCallback(
    (mouseMoveEvent: MouseEvent) => {
      if (isResizing) {
        const newWidth = window.innerWidth - mouseMoveEvent.clientX;
        if (newWidth > 250 && newWidth < 1000) {
            setRightSidebarWidth(newWidth);
        } else if (newWidth <= 250) {
            // Optional: Auto collapse if dragged too far right
            // setIsRightSidebarOpen(false); 
        }
      }
    },
    [isResizing]
  );

  useEffect(() => {
    window.addEventListener("mousemove", resize);
    window.addEventListener("mouseup", stopResizing);
    return () => {
      window.removeEventListener("mousemove", resize);
      window.removeEventListener("mouseup", stopResizing);
    };
  }, [resize, stopResizing]);


  // --- LOGIC ---
  const downloadFile = (fileName: string, content: string) => {
      const element = document.createElement("a");
      const file = new Blob([content], {type: 'text/plain'});
      element.href = URL.createObjectURL(file);
      element.download = fileName;
      document.body.appendChild(element);
      element.click();
      document.body.removeChild(element);
  };

  const createNewSession = () => {
    const newSession: ChatSession = {
      id: Date.now().toString(),
      title: 'Новый чат',
      agentId: currentAgentId,
      lastModified: new Date(),
      messages: [{ id: 'welcome', role: 'model', text: `Привет! Я ${currentAgent.name}. Готов к работе.`, timestamp: new Date() }]
    };
    setSessions(prev => [newSession, ...prev]);
    setCurrentSessionId(newSession.id);
  };

  const renameSession = (id: string, newTitle: string) => {
      setSessions(prev => prev.map(s => s.id === id ? { ...s, title: newTitle } : s));
      setEditingSessionId(null);
  };

  const deleteSession = (id: string) => {
      setSessions(prev => {
          const filtered = prev.filter(s => s.id !== id);
          if (currentSessionId === id && filtered.length > 0) {
              setCurrentSessionId(filtered[0].id);
          }
          return filtered;
      });
  };

  const simulateParamikoConnection = async () => {
     if (currentAgent.type === 'WATCHDOG') return;
     setIsConnected(false);
     setIsConnected(true);
     return Date.now().toString();
  };

  const simulateSFTPDeployment = async () => {
     if (currentAgent.type === 'WATCHDOG') return;
     setTimeout(() => {
         setIsRightSidebarOpen(true);
         setActiveRightTab('files');
     }, 1500);
  };

  const handleSend = async (e?: React.FormEvent, customPrompt?: string) => {
    if (e) e.preventDefault();
    const textToSend = customPrompt || input;
    if (!textToSend.trim() || loading) return;

    const userMsg: ChatMessage = {
      id: Date.now().toString(),
      role: 'user',
      text: textToSend,
      timestamp: new Date()
    };
    
    // Auto-title
    let updatedSessions = [...sessions];
    if (currentSession.messages.length <= 1) {
        updatedSessions = updatedSessions.map(s => s.id === currentSessionId ? { ...s, title: textToSend.slice(0, 30) } : s);
    }
    updatedSessions = updatedSessions.map(s => s.id === currentSessionId ? { ...s, messages: [...s.messages, userMsg], lastModified: new Date() } : s);
    
    setSessions(updatedSessions);
    setInput('');
    setLoading(true);

    const startTime = Date.now();
    
    // Check intents
    const lowerText = textToSend.toLowerCase();
    const isConnectIntent = lowerText.includes('подключ') || lowerText.includes('ssh') || lowerText.includes('connect');
    const isDeployIntent = lowerText.includes('развер') || lowerText.includes('deploy') || lowerText.includes('upload');
    
    // Simulate thinking delay
    await new Promise(r => setTimeout(r, 2000));

    let responseText = "";
    let artifact: ExtendedChatMessage['artifact'] = undefined;
    let thought = "Analyzing user intent. Checking available tools and permissions.";

    if (isConnectIntent) {
        await simulateParamikoConnection();
        thought += "\nIntent: SSH Connection.\nAction: Initializing Paramiko client.\nResult: Connected successfully.";
        responseText = `Соединение с ${sshConfig?.host || 'сервером'} установлено успешно.`;
        artifact = {
            type: 'terminal',
            title: 'SSH Connect',
            content: `ssh ${sshConfig?.username || 'root'}@${sshConfig?.host || '192.168.1.42'}`
        };
    } else if (isDeployIntent) {
        await simulateSFTPDeployment();
        thought += "\nIntent: Deployment.\nAction: Generating assets (Docker, Nginx).\nAction: SFTP Upload.\nResult: Files transferred.";
        responseText = "Файлы успешно сгенерированы и подготовлены к отправке. Вы можете просмотреть их в панели справа.";
        artifact = {
            type: 'code',
            title: 'Generate Deployment Assets',
            content: 'python3 scripts/deploy_stack.py --target prod'
        };
    } else {
        try {
            const response = await generateDevOpsAdvice(
                textToSend, 
                currentSession.messages.map(m => ({ role: m.role, parts: [{ text: m.text }] })),
                knowledgeBase,
                currentAgent
            );
            responseText = response.text;
            thought += "\nIntent: General Query.\nAction: Consulting knowledge base.\nResult: Generated advice.";
        } catch (err) {
            console.error(err);
            responseText = "Ошибка генерации ответа.";
        }
    }

    const duration = (Date.now() - startTime) / 1000;

    const modelMsg: ExtendedChatMessage = {
        id: (Date.now() + 1).toString(),
        role: 'model',
        text: responseText,
        timestamp: new Date(),
        artifact: artifact,
        thinkingDuration: duration,
        thinkingContent: thought
    };

    setSessions(prev => prev.map(s => s.id === currentSessionId ? { ...s, messages: [...s.messages, modelMsg] } : s));
    setLoading(false);
  };

  // --- SUB COMPONENTS ---

  // Refactored timestamp for vertical stacking
  const VerticalTimestamp = ({ date }: { date: Date }) => {
    const day = new Intl.DateTimeFormat('ru-RU', { day: '2-digit' }).format(date);
    const time = new Intl.DateTimeFormat('ru-RU', { hour: '2-digit', minute: '2-digit', second: '2-digit' }).format(date);
    
    // CHANGE: Made text lighter (zinc-400) and slightly larger/clearer
    return (
        <div className="flex flex-col items-center text-[10px] leading-tight text-zinc-400 font-mono mb-1 select-none opacity-80 hover:opacity-100 transition-opacity">
            <span>{day}</span>
            <span>{time}</span>
        </div>
    );
  };

  const ThinkingBlock = ({ duration, content, isLive = false }: { duration: number, content: string, isLive?: boolean }) => {
      const [expanded, setExpanded] = useState(isLive);
      
      return (
        <div className="think-container mb-3 mt-1 group">
            <div 
                className="flex cursor-pointer items-center transition-colors w-fit select-none"
                onClick={() => setExpanded(!expanded)}
            >
                <div className="flex items-center justify-center text-[13px] leading-[18px] text-zinc-500 font-[400] group-hover:text-zinc-300">
                    Thinking Process
                    <span className="ml-[6px] text-zinc-600 group-hover:text-zinc-400 font-mono text-[11px]">{duration.toFixed(2)}s</span>
                    <div className={`ml-[6px] transition-transform duration-200 ${expanded ? 'rotate-180' : 'rotate-0'}`}>
                        <ChevronDown className="w-3 h-3" />
                    </div>
                </div>
            </div>
            {expanded && (
                <div className="text-zinc-500 mt-2 text-[14px] animate-in slide-in-from-top-1 fade-in duration-200">
                    <div className="relative overflow-hidden">
                        <div className="bg-zinc-800 absolute left-1 top-1 bottom-1 w-[2px] rounded-full"></div>
                        <div className="relative pl-4 text-[13px] leading-relaxed opacity-80 whitespace-pre-wrap font-sans">
                            {content || "Analyzing request..."}
                        </div>
                    </div>
                </div>
            )}
        </div>
      );
  };

  const ToolExecutionBlock = ({ title, command, onClick }: { title: string, command: string, onClick: () => void }) => (
    <div 
        onClick={onClick}
        className="tool-name group hover:bg-zinc-800/50 hover:border-zinc-700 cursor-pointer text-pretty text-zinc-500 px-[12px] py-[6px] rounded-[14px] border border-zinc-800 border-[1px] w-fit flex gap-[8px] flex-start items-center font-[500] text-body-small max-w-full overflow-hidden mb-3 transition-all"
    >
        <div className="tool-call-message-icon w-[20px] h-[20px] relative my-[auto] flex items-center justify-center bg-zinc-900 rounded-full border border-zinc-800">
            <svg width="12" height="12" viewBox="0 0 17 16" fill="none" xmlns="http://www.w3.org/2000/svg" className="text-zinc-400">
                <path d="M14.9972 11.25V3.82146C14.9972 3.56505 14.7893 3.35718 14.5329 3.35718H3.39007C3.14379 3.35718 2.92578 3.57519 2.92578 3.82146V11.25C2.92578 11.4963 3.14379 11.7143 3.39007 11.7143H14.5329C14.7792 11.7143 14.9972 11.4963 14.9972 11.25Z" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round"></path>
                <path d="M6.17578 14.0358H11.7472" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round"></path>
                <path d="M7.10379 6.14307L5.71094 7.53592L7.10379 8.92878" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round"></path>
                <path d="M10.8184 6.14307L12.2112 7.53592L10.8184 8.92878" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round"></path>
            </svg>
        </div>
        <div className="flex-1 overflow-x-auto overflow-y-hidden scrollbar-hide whitespace-nowrap flex items-center gap-2">
            <span className="h-[17px] leading-[17px] font-[400] text-[13px] text-zinc-300">{title}</span>
            {command && (
                <div className="text-[11px] font-mono text-zinc-500 bg-zinc-900 px-1.5 py-0.5 rounded border border-zinc-800 hidden sm:block">
                    {command}
                </div>
            )}
        </div>
    </div>
  );

  return (
    <div className="flex h-screen bg-[#101011] text-zinc-100 font-sans overflow-hidden relative">
      {/* BACKGROUND BLOBS (New addition) */}
      <div id="content-wrapper">
          <div id="bg-ball"></div>
      </div>
      
      {/* 1. LEFT SIDEBAR */}
      <div 
        className={`flex-shrink-0 flex flex-col border-r border-zinc-800 bg-[#101011]/80 backdrop-blur-md transition-all duration-300 ease-in-out z-40 ${leftSidebarOpen ? 'w-[280px] translate-x-0' : 'w-0 -translate-x-full opacity-0 overflow-hidden'}`}
      >
        <div className="p-4 flex items-center justify-between h-[60px]">
            <h1 className="font-bold text-lg tracking-tight flex items-center gap-2 text-white">
                <Hexagon className="w-5 h-5 text-indigo-500 fill-indigo-500/20" />
                <span>NexusOps</span>
            </h1>
            <button onClick={() => setLeftSidebarOpen(false)} className="p-1.5 hover:bg-zinc-800 rounded-lg transition-colors text-zinc-500 hover:text-zinc-300">
                <PanelLeftClose className="w-4 h-4" />
            </button>
        </div>

        {/* Sessions List */}
        <div className="flex-1 overflow-y-auto px-2 py-2">
            <div className="px-2 mb-3 mt-2 flex items-center justify-between">
                <span className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest">Активные чаты</span>
                <button onClick={createNewSession} className="text-zinc-400 hover:text-white transition-colors p-1 hover:bg-zinc-800 rounded">
                    <Plus className="w-4 h-4" />
                </button>
            </div>
            <div className="space-y-1">
                {sessions.map(session => (
                    <div 
                        key={session.id}
                        className={`group relative px-3 py-2.5 cursor-pointer rounded-lg transition-all flex items-center justify-between ${currentSessionId === session.id ? 'bg-zinc-800/50 text-white shadow-sm' : 'text-zinc-400 hover:text-zinc-200 hover:bg-zinc-800/30'}`}
                        onClick={() => setCurrentSessionId(session.id)}
                    >
                        {editingSessionId === session.id ? (
                            <input 
                                autoFocus
                                value={editTitle}
                                onChange={(e) => setEditTitle(e.target.value)}
                                onBlur={() => renameSession(session.id, editTitle)}
                                onKeyDown={(e) => e.key === 'Enter' && renameSession(session.id, editTitle)}
                                className="bg-zinc-950 text-white text-xs px-2 py-1 rounded w-full outline-none border border-indigo-500"
                            />
                        ) : (
                            <div className="flex-1 overflow-hidden flex flex-col gap-0.5">
                                <div className="text-[13px] font-medium truncate pr-4">{session.title}</div>
                                <div className="text-[10px] text-zinc-600 truncate">
                                    {session.messages[session.messages.length-1].text.slice(0, 30)}...
                                </div>
                            </div>
                        )}

                        <div className="hidden group-hover:flex items-center gap-1 absolute right-2 bg-zinc-800 shadow-xl rounded-md p-0.5 border border-zinc-700">
                            <button 
                                onClick={(e) => { e.stopPropagation(); setEditingSessionId(session.id); setEditTitle(session.title); }}
                                className="p-1 hover:bg-zinc-700 rounded text-zinc-400 hover:text-white"
                            >
                                <Edit2 className="w-3 h-3" />
                            </button>
                            <button 
                                onClick={(e) => { e.stopPropagation(); deleteSession(session.id); }}
                                className="p-1 hover:bg-red-900/30 rounded text-zinc-400 hover:text-red-400"
                            >
                                <Trash2 className="w-3 h-3" />
                            </button>
                        </div>
                    </div>
                ))}
            </div>
        </div>

        {/* Bottom User Menu */}
        <div className="p-3 border-t border-zinc-800 bg-[#101011]/90">
             {showUserMenu && (
                 <div className="absolute bottom-[70px] left-3 right-3 bg-[#18181b] border border-zinc-700 rounded-xl shadow-2xl overflow-hidden z-50 animate-in slide-in-from-bottom-2 fade-in duration-200">
                     <div className="p-1 space-y-0.5">
                        <button className="flex items-center gap-3 px-3 py-2 w-full text-left text-[13px] text-zinc-300 hover:bg-zinc-800 rounded-lg transition-colors">
                            <User className="w-4 h-4 text-zinc-500" /> Профиль
                        </button>
                        <button className="flex items-center gap-3 px-3 py-2 w-full text-left text-[13px] text-zinc-300 hover:bg-zinc-800 rounded-lg transition-colors">
                            <CreditCard className="w-4 h-4 text-zinc-500" /> 
                            <span className="flex-1">Баланс</span>
                            <span className="text-emerald-500 font-mono">$42.00</span>
                        </button>
                     </div>
                     <div className="h-px bg-zinc-800 mx-1"></div>
                     <div className="p-1 space-y-0.5">
                        <button className="flex items-center gap-3 px-3 py-2 w-full text-left text-[13px] text-zinc-300 hover:bg-zinc-800 rounded-lg transition-colors">
                            <Globe className="w-4 h-4 text-zinc-500" /> Язык: Русский
                        </button>
                        <button className="flex items-center gap-3 px-3 py-2 w-full text-left text-[13px] text-zinc-300 hover:bg-zinc-800 rounded-lg transition-colors">
                            <Sun className="w-4 h-4 text-zinc-500" /> Тема: Тёмная
                        </button>
                        <button 
                            onClick={() => { setShowUserMenu(false); onViewChange && onViewChange(ViewState.SETTINGS); }}
                            className="flex items-center gap-3 px-3 py-2 w-full text-left text-[13px] text-zinc-300 hover:bg-zinc-800 rounded-lg transition-colors"
                        >
                            <Settings className="w-4 h-4 text-zinc-500" /> Настройки
                        </button>
                     </div>
                     <div className="h-px bg-zinc-800 mx-1"></div>
                     <div className="p-1">
                        <button className="flex items-center gap-3 px-3 py-2 w-full text-left text-[13px] text-red-400 hover:bg-red-950/20 rounded-lg transition-colors">
                            <LogOut className="w-4 h-4" /> Выйти
                        </button>
                     </div>
                 </div>
             )}

            <button 
                onClick={() => setShowUserMenu(!showUserMenu)}
                className={`flex items-center gap-3 w-full p-2 rounded-xl transition-all border ${showUserMenu ? 'bg-zinc-800 border-zinc-700' : 'hover:bg-zinc-800/50 border-transparent hover:border-zinc-800'}`}
            >
                <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-indigo-600 to-violet-600 flex items-center justify-center text-white font-bold text-xs shadow-lg shadow-indigo-900/20">
                    AO
                </div>
                <div className="flex-1 text-left overflow-hidden">
                    <div className="text-[13px] font-semibold text-white truncate">Admin Ops</div>
                    <div className="text-[10px] text-zinc-500 truncate">Pro Plan</div>
                </div>
                <div className="text-zinc-500">
                    {showUserMenu ? <ChevronDown className="w-4 h-4" /> : <ChevronUp className="w-4 h-4" />}
                </div>
            </button>
        </div>
      </div>

      {/* 2. CENTER STAGE (Chat) - Made transparent to show blobs */}
      <div className="flex-1 flex flex-col relative bg-transparent min-w-0 z-10">
         
         {!leftSidebarOpen && (
             <div className="absolute top-4 left-4 z-20 animate-in fade-in zoom-in duration-300">
                 <button onClick={() => setLeftSidebarOpen(true)} className="p-2 bg-zinc-900/90 backdrop-blur border border-zinc-800 rounded-lg text-zinc-400 hover:text-white transition-colors shadow-lg group">
                     <PanelLeft className="w-5 h-5 group-hover:scale-110 transition-transform" />
                 </button>
             </div>
         )}

         {/* Messages */}
         <div className="flex-1 overflow-y-auto p-4 scroll-smooth">
            {/* CHANGE: Fully expanded width to edges */}
            <div className="w-full px-4 space-y-6 pb-32 pt-4">
                {currentMessages.map((msg) => (
                    <div key={msg.id} className={`flex gap-3 ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                        
                        {/* BOT AVATAR + TIMESTAMP (Left Column) */}
                        {msg.role === 'model' && (
                            <div className="flex flex-col items-center gap-1 flex-shrink-0 w-12 pt-1">
                                <VerticalTimestamp date={msg.timestamp} />
                                <div className={`w-8 h-8 rounded-full flex items-center justify-center ${currentAgent.avatar} shadow-lg shadow-indigo-500/10`}>
                                    <Bot className="w-4 h-4 text-white" />
                                </div>
                            </div>
                        )}
                        
                        <div className={`flex flex-col ${msg.role === 'user' ? 'items-end' : 'items-start'} max-w-[85%]`}>
                             
                             {/* User Message */}
                             {msg.role === 'user' && (
                                <div className="flex flex-col items-end gap-1 w-full pl-10 group relative">
                                    <div className="flex items-center gap-2 mb-1">
                                         <VerticalTimestamp date={msg.timestamp} />
                                    </div>
                                    <div className="relative max-w-full">
                                        <div className="bg-[#27272a]/80 backdrop-blur-sm border border-zinc-800 text-[#ececec] px-5 py-3 rounded-[24px] rounded-br-sm text-[15px] leading-[26px] shadow-sm">
                                            <div className="whitespace-pre-wrap">{msg.text}</div>
                                        </div>

                                        {/* Action Buttons - Absolute bottom */}
                                        <div className="absolute -bottom-8 right-0 flex gap-1 opacity-0 group-hover:opacity-100 transition-opacity duration-200">
                                            {/* Copy */}
                                            <button className="p-1.5 hover:bg-zinc-800 rounded-lg text-zinc-500 hover:text-zinc-300 transition-colors" title="Copy">
                                                 <svg width="16" height="16" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M14.4341 2.61377C16.0808 2.69706 17.3908 4.05886 17.3912 5.72607V10.854C17.3912 12.5753 15.9952 13.9712 14.274 13.9712H13.9722V14.2729C13.9721 15.9939 12.577 17.389 10.856 17.3892H5.72711C4.00651 17.3888 2.61133 15.9936 2.6109 14.2729L2.60992 9.14111C2.60991 7.42233 4.00147 6.02739 5.72028 6.02393L6.02985 6.02295V5.72607C6.03028 4.00532 7.42526 2.61008 9.14606 2.60986H14.274L14.4341 2.61377ZM5.72321 7.52393C4.83174 7.52579 4.10995 8.24964 4.10992 9.14111L4.1109 14.2729C4.11112 15.1654 4.83479 15.8888 5.72711 15.8892H10.856C11.7486 15.889 12.4721 15.1655 12.4722 14.2729V9.13135C12.472 8.23771 11.7467 7.51273 10.8531 7.51416L5.72321 7.52393ZM9.14606 4.10986C8.25368 4.11008 7.53028 4.83375 7.52985 5.72607V6.02002L10.8502 6.01416C12.5734 6.01111 13.972 7.40814 13.9722 9.13135V12.4712H14.274C15.1668 12.4712 15.8912 11.7468 15.8912 10.854V5.72607C15.8908 4.88931 15.2541 4.20127 14.439 4.11865L14.274 4.10986H9.14606Z" fill="currentColor"></path></svg>
                                            </button>
                                            {/* Retry */}
                                            <button className="p-1.5 hover:bg-zinc-800 rounded-lg text-zinc-500 hover:text-zinc-300 transition-colors" title="Retry">
                                                <svg width="16" height="16" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M6.3515 3.08619C6.66589 2.81691 7.13956 2.85311 7.40912 3.16724C7.6786 3.48163 7.64226 3.95524 7.32806 4.22486L6.14252 5.24049H12.0722C15.043 5.2406 17.6806 7.4372 17.8036 10.2854C17.9336 13.3036 15.207 15.7404 12.0722 15.7405H5.55756C5.14344 15.7405 4.80771 15.4046 4.80756 14.9905C4.80756 14.5763 5.14334 14.2405 5.55756 14.2405H12.0722C14.5127 14.2404 16.3914 12.3639 16.3046 10.3499C16.2219 8.4354 14.3779 6.7406 12.0722 6.74049H6.0556L7.37006 8.05494C7.66288 8.34777 7.66275 8.82258 7.37006 9.11549C7.07716 9.40835 6.60239 9.40838 6.30951 9.11549L3.65521 6.46119C3.50755 6.31348 3.42845 6.11033 3.43646 5.90162C3.44466 5.69322 3.5389 5.49738 3.6972 5.36158L6.3515 3.08619Z" fill="currentColor"></path></svg>
                                            </button>
                                            {/* Edit */}
                                            <button className="p-1.5 hover:bg-zinc-800 rounded-lg text-zinc-500 hover:text-zinc-300 transition-colors" title="Edit">
                                                <svg width="16" height="16" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" clipRule="evenodd" d="M11.7937 3.58614C13.0694 2.31048 15.1382 2.31048 16.4138 3.58614C17.6893 4.86181 17.6894 6.93067 16.4138 8.20625L8.50463 16.1145C8.00491 16.6141 7.35652 16.9383 6.65698 17.0383L4.44213 17.3547C3.39388 17.5041 2.49571 16.6051 2.64526 15.5568L2.96166 13.343C3.0616 12.6434 3.38586 11.9951 3.88549 11.4953L11.7937 3.58614ZM4.94604 12.5559C4.67591 12.8261 4.50008 13.1766 4.44604 13.5549L4.12963 15.7697C4.12179 15.8279 4.17199 15.8784 4.23022 15.8703L6.44506 15.5539C6.82326 15.4998 7.17389 15.324 7.44409 15.0539L13.6374 8.85957L11.1394 6.36153L4.94604 12.5559ZM15.3533 4.64668C14.6634 3.95681 13.5441 3.95681 12.8542 4.64668L12.1999 5.30098L14.698 7.79903L15.3533 7.14473C16.0426 6.4549 16.0428 5.33643 15.3533 4.64668Z" fill="currentColor"></path></svg>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                             )}

                             {/* Model Message */}
                             {msg.role === 'model' && (
                                 <div className="w-full">
                                    {/* Thinking Process Block (Before Text) - Collapses when done (isLive=false) */}
                                    {msg.thinkingDuration && msg.thinkingContent && (
                                        <ThinkingBlock duration={msg.thinkingDuration} content={msg.thinkingContent} isLive={false} />
                                    )}

                                    {/* Tool Execution Block (Pill Style) */}
                                    {msg.artifact && (
                                        <ToolExecutionBlock 
                                            title={msg.artifact.title || 'Command Execution'} 
                                            command={msg.artifact.content || ''}
                                            onClick={() => {
                                                setIsRightSidebarOpen(true);
                                                setActiveRightTab('files');
                                                if (msg.artifact?.content?.includes('index.html')) {
                                                    setActiveFilePreview('index.html');
                                                }
                                            }}
                                        />
                                    )}
                                    
                                    {/* Actual Response Text */}
                                    {msg.text && (
                                        <div className="text-zinc-300 text-[15px] leading-relaxed whitespace-pre-wrap mt-1 pl-1">
                                            {msg.text}
                                        </div>
                                    )}
                                 </div>
                             )}
                        </div>
                    </div>
                ))}
                
                {/* Live Thinking Process (Streaming) - Expanded by default (isLive=true) */}
                {loading && (
                     <div className="flex gap-3 animate-in fade-in slide-in-from-bottom-2">
                         <div className="flex flex-col items-center gap-1 flex-shrink-0 w-12 pt-1">
                             <VerticalTimestamp date={new Date()} />
                             <div className={`w-8 h-8 rounded-full flex items-center justify-center ${currentAgent.avatar}`}>
                                <Loader2 className="w-4 h-4 text-white animate-spin" />
                            </div>
                         </div>
                        
                        <div className="flex-1 max-w-[85%]">
                            <ThinkingBlock duration={thinkingTime} content="Analyzing context and intent..." isLive={true} />
                        </div>
                     </div>
                )}
                <div ref={bottomRef} />
            </div>
         </div>

         {/* Floating Input Area */}
         <div className="absolute bottom-0 left-0 right-0 px-4 pb-6 pt-20 bg-gradient-to-t from-[#101011] via-[#101011]/90 to-transparent z-20">
             {/* CHANGE: Increased max-w to match full width request */}
             <div className="w-full max-w-[95%] mx-auto relative group">
                 {/* Gradient Glow Effect */}
                 <div className="absolute -inset-[1px] bg-gradient-to-r from-indigo-500/20 via-purple-500/20 to-pink-500/20 rounded-2xl opacity-0 group-hover:opacity-100 transition duration-700 blur-md"></div>
                 
                 <div className="relative bg-[#27272a]/90 backdrop-blur-md rounded-2xl border border-zinc-800 shadow-2xl flex flex-col p-2 focus-within:border-zinc-600 transition-colors">
                     <textarea 
                        value={input}
                        onChange={(e) => setInput(e.target.value)}
                        onKeyDown={(e) => { if(e.key === 'Enter' && !e.shiftKey) { handleSend(e); } }}
                        placeholder={`Сообщение для ${currentAgent.name}...`}
                        className="w-full bg-transparent border-none focus:ring-0 text-[14px] text-white placeholder-zinc-500 px-3 py-2 resize-none min-h-[48px] max-h-[200px]"
                        rows={1}
                     />
                     
                     <div className="flex justify-between items-center px-2 pb-1 mt-1">
                         <div className="flex gap-1">
                             <button className="p-1.5 text-zinc-400 hover:text-white hover:bg-zinc-800 rounded-lg transition-colors" title="Прикрепить файл">
                                 <Plus className="w-4 h-4" />
                             </button>
                             {currentAgent.type === 'USER_SIDE' && sshConfig && (
                                <button 
                                    onClick={() => handleSend(undefined, `Подключись к ${sshConfig.host}`)}
                                    className="p-1.5 px-2 bg-emerald-950/20 text-emerald-500 hover:bg-emerald-950/40 border border-emerald-900/50 rounded-lg transition-colors flex items-center gap-1.5"
                                    title={`SSH: ${sshConfig.host}`}
                                >
                                    <Wifi className="w-3 h-3" />
                                    <span className="text-[10px] font-medium hidden sm:inline">SSH Connect</span>
                                </button>
                             )}
                         </div>
                         <button 
                            onClick={(e) => handleSend(e)} 
                            disabled={!input.trim() || loading}
                            className="p-2 bg-white text-black rounded-lg hover:bg-zinc-200 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                         >
                            <ArrowUpCircle className="w-5 h-5" />
                         </button>
                     </div>
                 </div>
                 <div className="text-center mt-3 text-[10px] text-zinc-600 select-none">
                    NexusOps AI v2.0 • Может допускать ошибки
                 </div>
             </div>
         </div>
      </div>

      {/* 3. RESIZABLE SPLITTER (with Diamond/Cyan Glow) */}
      {isRightSidebarOpen && (
          <div 
            className={`w-1 cursor-col-resize hover:bg-cyan-500 hover:shadow-[0_0_15px_rgba(34,211,238,0.6)] hover:w-1 transition-all z-30 flex flex-col justify-center items-center ${isResizing ? 'bg-cyan-500 shadow-[0_0_15px_rgba(34,211,238,0.6)]' : 'bg-zinc-800/50'}`}
            onMouseDown={startResizing}
          >
              <div className="h-8 w-1 bg-zinc-700 rounded-full group-hover:bg-cyan-200"></div>
          </div>
      )}

      {/* 4. RIGHT SIDEBAR (Studio Panel) - Resizable & Closable */}
      {isRightSidebarOpen && (
        <div 
            ref={sidebarRef}
            className="flex-shrink-0 bg-[#09090b]/80 backdrop-blur-md border-l border-zinc-800 flex flex-col z-30"
            style={{ width: rightSidebarWidth }}
        >
            {/* Header Tabs */}
            <div className="flex items-center justify-between p-2 border-b border-zinc-800 bg-transparent">
                <div className="flex bg-zinc-900/50 rounded-lg p-1 w-full mr-2 border border-zinc-800/50">
                    <button 
                        onClick={() => setActiveRightTab('files')}
                        className={`flex-1 flex items-center justify-center gap-2 py-1.5 rounded-md text-[11px] font-medium transition-all ${activeRightTab === 'files' ? 'bg-zinc-800 text-white shadow-sm border border-zinc-700' : 'text-zinc-500 hover:text-zinc-300'}`}
                    >
                        <FileCode className="w-3 h-3" /> Файлы
                    </button>
                    <button 
                        onClick={() => setActiveRightTab('preview')}
                        className={`flex-1 flex items-center justify-center gap-2 py-1.5 rounded-md text-[11px] font-medium transition-all ${activeRightTab === 'preview' ? 'bg-zinc-800 text-white shadow-sm border border-zinc-700' : 'text-zinc-500 hover:text-zinc-300'}`}
                    >
                        <MonitorPlay className="w-3 h-3" /> Превью
                    </button>
                </div>
                <button 
                    onClick={() => setIsRightSidebarOpen(false)}
                    className="p-1.5 hover:bg-zinc-800 rounded text-zinc-500 hover:text-zinc-300 transition-colors"
                >
                    <X className="w-4 h-4" />
                </button>
            </div>

            <div className="flex-1 overflow-hidden relative">

                {/* FILES TAB */}
                {activeRightTab === 'files' && (
                    <div className="h-full flex flex-col overflow-hidden">
                        {/* File Explorer */}
                        <div className="flex-1 overflow-y-auto p-4">
                            <h3 className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest mb-4 flex items-center gap-2">
                                <FolderOpen className="w-3 h-3" /> Файловая система
                            </h3>
                            <div className="space-y-1">
                                {Object.entries(MOCK_FILES).map(([filename, content]) => (
                                    <div key={filename} className="group">
                                        <div 
                                            onClick={() => setActiveFilePreview(filename)}
                                            className={`flex items-center justify-between p-2 rounded-lg cursor-pointer border transition-all ${activeFilePreview === filename ? 'bg-zinc-800 border-zinc-700 text-white' : 'border-transparent hover:bg-zinc-900 hover:border-zinc-800 text-zinc-400'}`}
                                        >
                                            <div className="flex items-center gap-2 overflow-hidden">
                                                <FileText className={`w-4 h-4 flex-shrink-0 ${activeFilePreview === filename ? 'text-indigo-400' : 'text-zinc-500'}`} />
                                                <span className="text-[13px] truncate">{filename}</span>
                                            </div>
                                            <button 
                                                onClick={(e) => { e.stopPropagation(); downloadFile(filename, content); }}
                                                className="opacity-0 group-hover:opacity-100 p-1.5 hover:bg-zinc-700 rounded text-zinc-400 hover:text-white transition-all"
                                                title="Скачать"
                                            >
                                                <Download className="w-3 h-3" />
                                            </button>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>
                        
                        {/* Code Editor Preview */}
                        <div className="h-1/2 border-t border-zinc-800 bg-[#0c0c0c] flex flex-col">
                            <div className="flex items-center justify-between px-4 py-2 border-b border-zinc-800 bg-zinc-900/30">
                                <div className="flex items-center gap-2">
                                    <Code2 className="w-3 h-3 text-indigo-500" />
                                    <span className="text-xs text-zinc-400 font-mono">
                                        {activeFilePreview || 'Выберите файл'}
                                    </span>
                                </div>
                            </div>
                            <div className="flex-1 overflow-auto p-4">
                                {activeFilePreview ? (
                                    <pre className="text-[11px] font-mono text-zinc-300 whitespace-pre-wrap">
                                        {MOCK_FILES[activeFilePreview as keyof typeof MOCK_FILES]}
                                    </pre>
                                ) : (
                                    <div className="h-full flex items-center justify-center text-zinc-700 text-xs">
                                        Нет выбранного файла
                                    </div>
                                )}
                            </div>
                        </div>
                    </div>
                )}

                {/* PREVIEW TAB */}
                {activeRightTab === 'preview' && (
                    <div className="h-full flex flex-col bg-[#0c0c0c] p-4">
                        <div className="flex-1 bg-white border border-zinc-800 rounded-xl overflow-hidden relative shadow-2xl">
                            {/* Fake Browser Chrome */}
                            <div className="bg-zinc-100 border-b border-zinc-200 p-2 flex items-center gap-2">
                                <div className="flex gap-1.5">
                                    <div className="w-2.5 h-2.5 rounded-full bg-red-400"></div>
                                    <div className="w-2.5 h-2.5 rounded-full bg-yellow-400"></div>
                                    <div className="w-2.5 h-2.5 rounded-full bg-green-400"></div>
                                </div>
                                <div className="flex-1 bg-white border border-zinc-200 rounded px-2 py-0.5 text-[10px] text-zinc-500 text-center flex items-center justify-center gap-1 shadow-sm">
                                    <Globe className="w-2 h-2" />
                                    localhost:8080
                                </div>
                            </div>
                            
                            {/* Iframe Content */}
                            <iframe 
                                srcDoc={MOCK_FILES['index.html']}
                                className="w-full h-full border-none"
                                title="Preview"
                                sandbox="allow-scripts"
                            />
                        </div>
                        <div className="mt-4 text-center">
                            <div className="inline-flex items-center gap-2 px-3 py-1.5 bg-zinc-900 border border-zinc-800 rounded-full text-[10px] text-zinc-400">
                                <div className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse"></div>
                                Сервер запущен (Port 8080)
                            </div>
                        </div>
                    </div>
                )}
            </div>
        </div>
      )}
    </div>
  );
};